### ISSUE TITLE
Example of stubbing multiple requests

### ISSUE THREAD

**Issue by gaynetdinov** [tank-bohr/bookish_spork#18]
Hi. 

I see from the code that it seems to be possible to stub several requests at once, i.e. when I need to tests multiple pages response. This would require stubbing request according to the request query I think. For example response contains some `next` marker or url for the next page. 
So I'd need to stub it like that
```
:bookish_spork.stub_request("/", 200, Poison.encode!(first_page_data))
:bookish_spork.stub_request("/?next_page=2", 200, Poison.encode!(second_page_data))
```
Would it be possible? 
If yes, could you please add an example to your example apps how one could use it?

**Comment by tank-bohr** [comment]
Hi.

For the sake of simplicity I didn't want to add this feature. I believe there is not so necessary to match request by query. There are much more powerful means to achieve the desired result. You can inspect request after it occurred with `capture_request` and validate its correctness not just by url but much deeper. In your case you do not actually need to match query string. You know the order and you should just stub the first request and the second one

```elixir
:bookish_spork.stub_request(200, Poison.encode!(first_page_data))
:bookish_spork.stub_request(200, Poison.encode!(second_page_data))
```

But if you still want to do some tricky stuff, you can stub with fun

```elixir
:bookish_spork.stub_request fn req ->
  case :bookish_spork_request:uri(req) do
    '/?next_page=2' ->
      :bookish_spork_response:new(200, Poison.encode!(second_page_data))
    # ...
  end
end
```


https://github.com/tank-bohr/bookish_spork/tree/c73e404ae9b4154487f8a8d5794ecc9962f391cf#more-complex-expectations

**Comment by gaynetdinov** [comment]
Thank you!
