### ISSUE TITLE
По поводу работы

### ISSUE THREAD

**Issue by Dmitryi** [tank-bohr/bookish_spork#21]
Здравствуйте, Алексей.
Заранее извиняюсь, что пишу в github.
Я Дмитрий. 27 августа на вашу почту отправлял вакансии Ruby on Rails dev.
Хочу узнать вы готовы рассмотреть предложение о работе?

**Comment by Dmitryi** [comment]
Алексей спасибо за ответ.
На данный момент вакансий по Эрланг нет.
Учту на будущее.

**Comment by vtm9** [comment]
kek
