### ISSUE TITLE
Problems with gun

### ISSUE THREAD

**Issue by gaynetdinov** [tank-bohr/bookish_spork#22]
Hello. 

I recently started to use `bookish_spork` instead of `bypass`, because `bookish_spork` does not have `cowboy` dependency and I wanted to use `gun`. However I got some problems testing HTTP requests with `gun`. The problem is that when I stub multiple requests, `gun` fails to get second response or gets it after ~5 seconds timeout. In order to demonstrate it I've created a test repo for you https://github.com/gaynetdinov/gun_with_spork.

There is `HttpClient` module which is a simple wrapper around `gun` (because `gun` is quite verbose) and there is simple test file with several test cases there.
`gun` works ok when I create a separate connection per request, but if I want to reuse already established connection (see https://github.com/gaynetdinov/gun_with_spork/blob/master/test/gun_with_spork_test.exs#L28) I either get second response after 4-5 seconds or get the following error
```
$ mix test

[error] Process #PID<0.210.0> raised an exception
** (CaseClauseError) no case clause matching: {:error, :closed}
    (bookish_spork) /Users/damir/projects/gun_with_spork/deps/bookish_spork/src/bookish_spork_server.erl:95: :bookish_spork_server.receive_request/2
    (bookish_spork) /Users/damir/projects/gun_with_spork/deps/bookish_spork/src/bookish_spork_server.erl:82: anonymous fn/3 in :bookish_spork_server.accept/3
```

Do you know why this is happening? Or maybe you could suggest some workarounds? 
Thank you for your time!

**Comment by gaynetdinov** [comment]
As I understand, after every request `bookish_spork` closes the connection, so `gun` reports that the worker which initiated the connection lost it. The default `retry_timeout` is `5000`.

**Comment by tank-bohr** [comment]
@gaynetdinov Thank you for the feedback. It's true. keepalive mechanics have not been implemented. I'l fix it ASAP
