### ISSUE TITLE
Port 5432 is default port of postgesql

### ISSUE THREAD

**Issue by gaynetdinov** [tank-bohr/bookish_spork#5]
If postgresql is running, `bookish_spork` won't work silently, because port is already in use.

**Comment by tank-bohr** [comment]
Hi! Thank you for participating. I didn't think it's a postgres default port. My bad. I'll change it of course.

But about "won't work silently" I don't think it can be done anything. You get
```
{'EXIT',
                {{badmatch,
                     {error,
                         {{badmatch,{error,eaddrinuse}}
...
```

What would you prefer to see here?

BTW as a workaround you can use `bookish_spork:start_server/1` with any port you like

**Comment by gaynetdinov** [comment]
Yeah, sorry didn't have time to answer. Thanks for the fix and for the suggested workaround. 
Cheers.
